package com.norris.believer.Bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DDAUDIO_BEAN".
*/
public class DDAudioBeanDao extends AbstractDao<DDAudioBean, Long> {

    public static final String TABLENAME = "DDAUDIO_BEAN";

    /**
     * Properties of entity DDAudioBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Position = new Property(0, Long.class, "position", false, "POSITION");
        public final static Property Id = new Property(1, Long.class, "id", true, "_id");
        public final static Property AudioUrl = new Property(2, String.class, "audioUrl", false, "AUDIOURL");
        public final static Property Type = new Property(3, String.class, "type", false, "TYPE");
    }


    public DDAudioBeanDao(DaoConfig config) {
        super(config);
    }
    
    public DDAudioBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DDAUDIO_BEAN\" (" + //
                "\"POSITION\" INTEGER," + // 0: position
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 1: id
                "\"AUDIOURL\" TEXT," + // 2: audioUrl
                "\"TYPE\" TEXT);"); // 3: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DDAUDIO_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DDAudioBean entity) {
        stmt.clearBindings();
 
        Long position = entity.getPosition();
        if (position != null) {
            stmt.bindLong(1, position);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(2, id);
        }
 
        String audioUrl = entity.getAudioUrl();
        if (audioUrl != null) {
            stmt.bindString(3, audioUrl);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(4, type);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DDAudioBean entity) {
        stmt.clearBindings();
 
        Long position = entity.getPosition();
        if (position != null) {
            stmt.bindLong(1, position);
        }
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(2, id);
        }
 
        String audioUrl = entity.getAudioUrl();
        if (audioUrl != null) {
            stmt.bindString(3, audioUrl);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(4, type);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1);
    }    

    @Override
    public DDAudioBean readEntity(Cursor cursor, int offset) {
        DDAudioBean entity = new DDAudioBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // position
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // audioUrl
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // type
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DDAudioBean entity, int offset) {
        entity.setPosition(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setAudioUrl(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setType(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DDAudioBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DDAudioBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DDAudioBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
